export const EVENTS = {
    PAGE_VIEW: "PAGE_VIEW",
    BUTTON_CLICK: "BUTTON_CLICK",
    REQUEST_RECEIVED: "REQUEST_RECEIVED",
    REQUEST_SUCCESS: "REQUEST_SUCCESS",
    REQUEST_ERROR: "REQUEST_ERROR",
    ABUSE_TRIGGERED: "ABUSE_TRIGGERED",
    STEP_STARTED: "STEP_STARTED",
    STEP_COMPLETED: "STEP_COMPLETED",
    STEP_FAILED: "STEP_FAILED"
};
